version: '3'
services:
  gogs_db:
    image: mysql:5.7
    volumes:
      - gogs_mysql:/var/lib/mysql
    container_name: gogs_db
    environment:
      HOSTNAME: q68u8b2buodpme2n.cbetxkdyhwsb.us-east-1.rds.amazonaws.com
      MYSQL_DATABASE: n54nclld1dlcnely
      MYSQL_USER: qg9e86d98smwwn3g
      MYSQL_PASSWORD: tnf972sbcfp3ffqd
    ports:
      - "3306"
  gogs:
    image: gogs/gogs
    volumes:
      - gogs_data:/data
    container_name: gogs
    ports:
      - "10022:22"
      - "10080:3000"
volumes:
  gogs_mysql:
  gogs_data:


